"""Frozen Card 2: Hamiltonian generated by connected-correlation energy.

Quantum kinematics, elementary factors, initial state, clock and controls are
supplied. Diagnostic measurements are not generated physical records.
"""
from itertools import combinations
import numpy as np

PAULI = (
    np.array([[0, 1], [1, 0]], dtype=complex),
    np.array([[0, -1j], [1j, 0]], dtype=complex),
    np.array([[1, 0], [0, -1]], dtype=complex),
)


def tensor(items):
    out = np.array([[1]], dtype=complex)
    for item in items:
        out = np.kron(out, item)
    return out


def operators(n):
    if type(n) is not int or n < 2:
        raise ValueError("at least two elementary qubits required")
    eye = np.eye(2, dtype=complex)
    return [[tensor([p if i == site else eye for i in range(n)])
             for p in PAULI] for site in range(n)]


def correlations(rho, ops):
    n = len(ops)
    means = np.array([[np.trace(rho @ q).real for q in row] for row in ops])
    cov = {}
    for i, j in combinations(range(n), 2):
        cov[i, j] = np.array([
            [np.trace(rho @ ops[i][a] @ ops[j][b]).real - means[i, a]*means[j, b]
             for b in range(3)] for a in range(3)])
    return means, cov


def energy(rho, ops, kappa=1.0):
    _, cov = correlations(rho, ops)
    return kappa/2 * sum(float(np.sum(c*c)) for c in cov.values())


def hamiltonian(rho, ops, kappa=1.0):
    if not np.isfinite(kappa) or kappa <= 0:
        raise ValueError("finite positive kappa required")
    means, cov = correlations(rho, ops)
    h = np.zeros_like(rho, dtype=complex)
    for (i, j), c in cov.items():
        for a in range(3):
            for b in range(3):
                h += kappa*c[a, b]*(ops[i][a] @ ops[j][b]
                    - means[j, b]*ops[i][a] - means[i, a]*ops[j][b])
    return h


def generator(rho, ops, kappa=1.0, local_controls=None):
    h = hamiltonian(rho, ops, kappa)
    if local_controls is not None:
        v = np.asarray(local_controls, dtype=float)
        if v.shape != (len(ops), 3) or not np.all(np.isfinite(v)):
            raise ValueError("one finite real coefficient per local Pauli required")
        for i, row in enumerate(ops):
            for a, q in enumerate(row):
                h += v[i, a]*q
    return -1j*(h @ rho - rho @ h)


def attempted_partition(rho, ops):
    """Exact graph proposal, not a certificate of generated S/E or persistence.

    On floating input the output is illustrative only: roundoff is not an exact
    zero certificate. No near-zero threshold, tie-breaking observer or record law.
    """
    _, cov = correlations(rho, ops)
    neighbors = {i: set() for i in range(len(ops))}
    for (i, j), c in cov.items():
        if np.any(c != 0):
            neighbors[i].add(j)
            neighbors[j].add(i)
    remaining = set(neighbors)
    blocks = []
    while remaining:
        todo = [min(remaining)]
        block = set()
        while todo:
            i = todo.pop()
            if i in block:
                continue
            block.add(i)
            todo.extend(neighbors[i] - block)
        remaining -= block
        blocks.append(sorted(block))
    return {"graph_components": blocks, "partition": None,
            "carrier": None, "readout": None, "interface": None,
            "reason": "No generated S/E designation or common-carrier/readout proof"}
