"""Exact evidence generation/checking with code hashes; stdlib only."""
import argparse
from fractions import Fraction
import hashlib
import json
from pathlib import Path
import platform
import sys
import unittest
from controls import run_controls

ROOT = Path(__file__).resolve().parent


def encode(value):
    if isinstance(value, Fraction):
        return {"rational": [value.numerator, value.denominator]}
    raise TypeError(type(value))


def tables(evidence):
    c = evidence['controls']
    e, r, u = c['C02_all_feedback_policies'], c['C04_rank_bound'], c['C12_precedence_vs_static_latent']
    lines = ['# Generated exact control table', '',
             'Generated by run.py from RESULTS.json computations; no hand-transcribed results.', '',
             '| Check | Exact result | Meaning |', '|---|---|---|',
             f"| Adaptive policy comparisons | {e['comparisons']} | All 128 depth-three binary feedback policies, eight initial states |",
             f"| Record probability cells | {e['record_cells']} | Original equations versus independent fixed transition table |",
             f"| Maximum record difference | {e['maximum_exact_difference']} | Exact rational equality in the finite fixtures |",
             f"| Response matrix rank / determinant | {r['rank']} / {r['determinant']} | Excludes classical fixed hidden-state models with at most three states |",
             f"| Urn / static-mixture word cells | {u['enumerated_word_cells']} | Lengths one through six |",
             f"| Urn / static-mixture maximum difference | {u['maximum_exact_difference']} | Passive observation equivalence |",
             f"| Next success after forced success: urn / static mixture | {u['after_do_first_success']['urn_next_success']} / {u['after_do_first_success']['static_mixture_next_success']} | Restricted causal comparator is separated |",
             f"| Urn pair covariance | {u['pair_covariance']} | Historical correlations do not establish evolving fundamental laws |",
             f"| Postulated birth probability after three steps | {c['C13_zero_to_one']['P_born']} | Requires a supplied birth kernel |", '',
             '## Two-bit shift-register response matrix', '',
             '| Preparation / response | 00 | 01 | 10 | 11 |', '|---|---|---|---|---|']
    for word, row in zip(r['preparations'], r['matrix']):
        lines.append('| '+''.join(map(str, word))+' | '+' | '.join(map(str, row))+' |')
    return '\n'.join(lines)+'\n'


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument('--check', action='store_true')
    args = parser.parse_args()
    ran = unittest.TextTestRunner(verbosity=2).run(
        unittest.defaultTestLoader.discover(str(ROOT), pattern='test_controls.py'))
    if not ran.wasSuccessful():
        return 1
    evidence = {"schema": "META_LAW_STANDARD_CONTROLS_V1",
        "scope": "ISSUE_5_FOUNDATIONS_ONLY_NO_CANDIDATE_NO_CARD",
        "review": "DRAFT_PENDING_EXTERNAL_REVIEW_SAME_AUTHOR_CHECKS",
        "python": platform.python_version(), "tests": ran.testsRun,
        "code_sha256": {name: hashlib.sha256((ROOT/name).read_bytes()).hexdigest()
                        for name in ('controls.py', 'test_controls.py', 'run.py')},
        "controls": run_controls()}
    output = json.dumps(evidence, default=encode, indent=2, sort_keys=True, allow_nan=False)+'\n'
    path = ROOT/'RESULTS.json'
    table_path = ROOT/'TABLES.md'
    table_text = tables(evidence)
    if args.check:
        if (not path.is_file() or path.read_text() != output or
                not table_path.is_file() or table_path.read_text() != table_text):
            print('FAIL: missing/stale/different results, code hash or Python version', file=sys.stderr)
            return 1
        print('18 exact tests PASS; evidence matches. No scientific approval or Card authorization.')
    else:
        path.write_text(output)
        table_path.write_text(table_text)
        print('Wrote exact RESULTS.json; builder checks only.')
    return 0


if __name__ == '__main__':
    sys.exit(main())
